name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: |
          yarn install
          npm install -g firebase-tools
          firebase setup:emulators:database

      - name: Build
        run: yarn build

      - name: Setup background services
        run: echo '{"rules":{".read":true,".write":true}}' > database.rules.json && yarn start &

      - name: Run tests
        run: firebase emulators:exec "yarn test"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
