name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: |
          yarn install
          npm install -g firebase-tools

      - name: Build
        run: yarn build

      - name: Setup background services
        run: echo {"rules":{".read":true,".write":true}} > database.rules.json && yarn start &

      - name: Run tests
        run: firebase emulators:start "yarn test"
